### ISSUE TITLE
Need help with installation on an already existing AWS Kubernetes cluster

### ISSUE THREAD

**Issue by wysow** [continuouspipe/continuouspipe#37]
Hello,

First thanks to release this tool as opensource!

Just managed to do all the steps in the `install` documentation, the UI IP is then using an ELB public IP like `XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX-YYYYYYYYYY.eu-west-1.elb.amazonaws.com` which seems to initialize an angular application but after some time it redirect to a private IP like `http://100.67.XXX.XXX/auth/authenticate?callback=http%3A%2F...` which obviously is not working.

Do you see what I've done wrong? Maybe it's my kubernetes cluster configuration?

Thanks for your help.

**Comment by wysow** [comment]
Just retried to re-create a cluster with a public topology (using kops)... it does have the same behavior...

**Comment by wysow** [comment]
Not sure if it worth to mention but I get this kind or error in Sentry:
```
[console] Error thrown while running command "-e=prod continuouspipe:message:pull-and-consume --connection=main". Message: "Socket error: could not connect to host."
```
about 20 times and after nothing...

**Comment by wysow** [comment]
OK found that it comes from a wrong URL in my `RIVER_API_URL` env variable but as I'm new to Kubernetes I can't find how to do a new deploy after updating it...

**Comment by sroze** [comment]
Yes, the RIVER_API_URL should be the URL of the public service for the `api`. The configuration is done using a ConfigMap. In order to manually update the ConfigMap of your Kubernetes cluster, you can use:
```
kubectl --namespace=[your-namespace] edit configmap main-config
```

Once you have saved and the config has been saved, you can delete the api **pod** to have Kubernetes to re-create another one.
```
kubectl --namespace=[your-namespace] get pods
kubectl --namespace=[your-namespace] delete pod api-[the-generated-numbers]
```

**Comment by wysow** [comment]
Thanks a lot @sroze but should be the UI pod that needs to be re-created instead of the API one no?

**Comment by wysow** [comment]
OK @sroze worked like a charm when recreating the UI pod thanks!

**Comment by sroze** [comment]
Great to hear 😃
