### ISSUE TITLE
display issue

### ISSUE THREAD

**Issue by OskarStark** [continuouspipe/continuouspipe#55]
hey, don't know where it come from, but it looks weird:
![screenshot 2018-03-27 10 47 05](https://user-images.githubusercontent.com/995707/37956690-521f6656-31ac-11e8-87ff-e41611cfe5c0.png)

`goodfor` -> `good for`
`thisautomation` -> `this automation`
`thissort` -> `this sort`

**Comment by OskarStark** [comment]
shall i create a ticket for companienv and close here?

**Comment by sroze** [comment]
I think that companienv is the best place to open an issue.

**Comment by sroze** [comment]
Closed in favor of https://github.com/sroze/companienv/issues/17
