### ISSUE TITLE
companienv error

### ISSUE THREAD

**Issue by OskarStark** [continuouspipe/continuouspipe#57]
![screenshot 2018-03-29 08 30 52](https://user-images.githubusercontent.com/995707/38073502-a239773c-332b-11e8-8ed1-2bf135e120fd.png)

why does it ask for 2 variables, and then nothing happens all the time?

**Comment by sroze** [comment]
This has been fixed in the following PR in Companienv: https://github.com/sroze/companienv/pull/13. I just released [0.0.8](https://github.com/sroze/companienv/releases/tag/0.0.8) which contains the fix.

**Comment by sroze** [comment]
Will be fixed by #58 :)

**Comment by OskarStark** [comment]
thank you for the fast feedback 🙌

**Comment by sroze** [comment]
Fixed by #58.
