### ISSUE TITLE
Private Docker image storage on Google Cloud Platform

### ISSUE THREAD

**Issue by lngphp** [continuouspipe/continuouspipe#73]
Is it possible to use ContinuousPipe with `Private Docker image storage on Google Cloud Platform`?

**Comment by sirago** [comment]
I'm trying to figure this out too. I can't get the correct values for Custom registry...

**Comment by Simperfit** [comment]
Yes it's possible; use the following:

```
Server / Name : eu.gcr.io (or xx.gcr.io)
Username: _json_key
Email: email@google.fr from service account
password: the access json key you get from service account
```
