### ISSUE TITLE
Bitbucket Integration 403 Forbidden

### ISSUE THREAD

**Issue by lngphp** [continuouspipe/continuouspipe#74]
Installing the ContinuousPipe Integration in Bitbucket

`https://authenticator.continuouspipe.io/connect/service/bitbucket/addon/` returns 403 Forbidden

**Comment by sroze** [comment]
But anyway, you should use `https://you-api-endpoint/auth/connect/service/bitbucket/addon/`; the `.continouspipe.io` is a remaining of the SaaS version so please don't use it :)
